KJFK:
  city: New York JFK
  lat: 40.6413
  lon: -73.7781
  timezone: America/New_York
KEWR:
  city: Newark
  lat: 40.6895
  lon: -74.1745
  timezone: America/New_York
KLGA:
  city: New York LaGuardia
  lat: 40.7769
  lon: -73.874
  timezone: America/New_York
KORD:
  city: Chicago O'Hare
  lat: 41.9742
  lon: -87.9073
  timezone: America/Chicago
KMCO:
  city: Orlando
  lat: 28.4312
  lon: -81.3081
  timezone: America/New_York
KLAS:
  city: Las Vegas
  lat: 36.084
  lon: -115.1537
  timezone: America/Los_Angeles
KCLT:
  city: Charlotte
  lat: 35.2144
  lon: -80.9434
  timezone: America/New_York
KSLC:
  city: Salt Lake City
  lat: 40.7884
  lon: -111.9778
  timezone: America/Denver
KPDX:
  city: Portland
  lat: 45.5887
  lon: -122.5975
  timezone: America/Los_Angeles
KTPA:
  city: Tampa
  lat: 27.9756
  lon: -82.5332
  timezone: America/New_York
KSTL:
  city: St Louis
  lat: 38.7487
  lon: -90.37
  timezone: America/Chicago
KBNA:
  city: Nashville
  lat: 36.1245
  lon: -86.6782
  timezone: America/Chicago
KRDU:
  city: Raleigh-Durham
  lat: 35.8776
  lon: -78.7875
  timezone: America/New_York
KDTW:
  city: Detroit
  lat: 42.2124
  lon: -83.3534
  timezone: America/New_York
KSAN:
  city: San Diego
  lat: 32.7336
  lon: -117.1897
  timezone: America/Los_Angeles
KMCI:
  city: Kansas City
  lat: 39.2976
  lon: -94.7139
  timezone: America/Chicago
KBWI:
  city: Baltimore
  lat: 39.1754
  lon: -76.6684
  timezone: America/New_York
KMEM:
  city: Memphis
  lat: 35.0424
  lon: -89.9767
  timezone: America/Chicago
KSMF:
  city: Sacramento
  lat: 38.6954
  lon: -121.5911
  timezone: America/Los_Angeles
# KABQ: weird distribution
#   city: Albuquerque
#   lat: 35.0402
#   lon: -106.6091
#   timezone: America/Denver
KIND:
  city: Indianapolis
  lat: 39.7173
  lon: -86.2944
  timezone: America/Indiana/Indianapolis
KFLL:
  city: Fort Lauderdale
  lat: 26.0726
  lon: -80.1527
  timezone: America/New_York
KPIT:
  city: Pittsburgh
  lat: 40.4915
  lon: -80.2329
  timezone: America/New_York
KCLE:
  city: Cleveland
  lat: 41.4117
  lon: -81.8498
  timezone: America/New_York
KMKE:
  city: Milwaukee
  lat: 42.9472
  lon: -87.8966
  timezone: America/Chicago
KSJC:
  city: San Jose
  lat: 37.3639
  lon: -121.9289
  timezone: America/Los_Angeles
KOAK:
  city: Oakland
  lat: 37.7213
  lon: -122.2208
  timezone: America/Los_Angeles
KCVG:
  city: Cincinnati
  lat: 39.0488
  lon: -84.6678
  timezone: America/New_York
KOMA:
  city: Omaha
  lat: 41.3032
  lon: -95.8941
  timezone: America/Chicago
KICT:
  city: Wichita
  lat: 37.6499
  lon: -97.4331
  timezone: America/Chicago
KTUL:
  city: Tulsa
  lat: 36.1984
  lon: -95.8881
  timezone: America/Chicago
KELP:
  city: El Paso
  lat: 31.8067
  lon: -106.3778
  timezone: America/Denver
KBUF:
  city: Buffalo
  lat: 42.9405
  lon: -78.7322
  timezone: America/New_York
KPBI:
  city: West Palm Beach
  lat: 26.6832
  lon: -80.0956
  timezone: America/New_York
KRNO:
  city: Reno
  lat: 39.4991
  lon: -119.7681
  timezone: America/Los_Angeles
KLIT:
  city: Little Rock
  lat: 34.7294
  lon: -92.2243
  timezone: America/Chicago
KDSM:
  city: Des Moines
  lat: 41.534
  lon: -93.6631
  timezone: America/Chicago
KCOS:
  city: Colorado Springs
  lat: 38.8058
  lon: -104.7009
  timezone: America/Denver
KRIC:
  city: Richmond
  lat: 37.5052
  lon: -77.3197
  timezone: America/New_York
KBHM:
  city: Birmingham
  lat: 33.5629
  lon: -86.7535
  timezone: America/Chicago
KMSN:
  city: Madison
  lat: 43.1399
  lon: -89.3375
  timezone: America/Chicago
KSDF:
  city: Louisville
  lat: 38.1741
  lon: -85.7361
  timezone: America/New_York
KTUS:
  city: Tucson
  lat: 32.1161
  lon: -110.941
  timezone: America/Phoenix
KMSY:
  city: New Orleans
  lat: 29.9934
  lon: -90.258
  timezone: America/Chicago
KJAX:
  city: Jacksonville
  lat: 30.4941
  lon: -81.6879
  timezone: America/New_York
KCHS:
  city: Charleston
  lat: 32.8987
  lon: -80.0405
  timezone: America/New_York
KBOI:
  city: Boise
  lat: 43.5644
  lon: -116.2228
  timezone: America/Boise
KGRR:
  city: Grand Rapids
  lat: 42.8808
  lon: -85.5228
  timezone: America/New_York
KALB:
  city: Albany
  lat: 42.7483
  lon: -73.8017
  timezone: America/New_York
KPVD:
  city: Providence
  lat: 41.7267
  lon: -71.4325
  timezone: America/New_York
KBDL:
  city: Hartford
  lat: 41.9389
  lon: -72.6832
  timezone: America/New_York
KPWM:
  city: Portland ME
  lat: 43.6462
  lon: -70.3093
  timezone: America/New_York
KBTV:
  city: Burlington VT
  lat: 44.4719
  lon: -73.1533
  timezone: America/New_York
KSYR:
  city: Syracuse
  lat: 43.1112
  lon: -76.1063
  timezone: America/New_York
KROC:
  city: Rochester NY
  lat: 43.1189
  lon: -77.6724
  timezone: America/New_York
KORF:
  city: Norfolk
  lat: 36.8946
  lon: -76.2012
  timezone: America/New_York
KGSP:
  city: Greenville SC
  lat: 34.8957
  lon: -82.2189
  timezone: America/New_York
KSAV:
  city: Savannah
  lat: 32.1276
  lon: -81.2021
  timezone: America/New_York
KCAE:
  city: Columbia SC
  lat: 33.9388
  lon: -81.1195
  timezone: America/New_York
KPNS:
  city: Pensacola
  lat: 30.4734
  lon: -87.1866
  timezone: America/Chicago
KTLH:
  city: Tallahassee
  lat: 30.3965
  lon: -84.3503
  timezone: America/New_York
KHSV:
  city: Huntsville
  lat: 34.6372
  lon: -86.7751
  timezone: America/Chicago
KMOB:
  city: Mobile
  lat: 30.6912
  lon: -88.2461
  timezone: America/Chicago
KCMH:
  city: Columbus OH
  lat: 39.9981
  lon: -82.8919
  timezone: America/New_York
KDAY:
  city: Dayton
  lat: 39.9024
  lon: -84.2194
  timezone: America/New_York
KFWA:
  city: Fort Wayne
  lat: 40.9785
  lon: -85.1951
  timezone: America/New_York
KSGF:
  city: Springfield MO
  lat: 37.2457
  lon: -93.3886
  timezone: America/Chicago
KFSD:
  city: Sioux Falls
  lat: 43.582
  lon: -96.7419
  timezone: America/Chicago
KLEX:
  city: Lexington
  lat: 38.0365
  lon: -84.6059
  timezone: America/New_York
KPIA:
  city: Peoria
  lat: 40.6642
  lon: -89.6933
  timezone: America/Chicago
KFAR:
  city: Fargo
  lat: 46.9207
  lon: -96.8158
  timezone: America/Chicago
KDLH:
  city: Duluth
  lat: 46.8421
  lon: -92.1936
  timezone: America/Chicago
KTOL:
  city: Toledo
  lat: 41.5868
  lon: -83.8076
  timezone: America/New_York
# KSHV:
#   city: Shreveport
#   lat: 32.4466
#   lon: -93.8256
#   timezone: America/Chicago
KJAN:
  city: Jackson MS
  lat: 32.3112
  lon: -90.0759
  timezone: America/Chicago
KBTR:
  city: Baton Rouge
  lat: 30.5332
  lon: -91.1497
  timezone: America/Chicago
KCRP:
  city: Corpus Christi
  lat: 27.7704
  lon: -97.5012
  timezone: America/Chicago
KAMA:
  city: Amarillo
  lat: 35.2194
  lon: -101.706
  timezone: America/Chicago
KLBB:
  city: Lubbock
  lat: 33.6636
  lon: -101.8228
  timezone: America/Chicago
KMAF:
  city: Midland TX
  lat: 31.9425
  lon: -102.2019
  timezone: America/Chicago
KTYS:
  city: Knoxville
  lat: 35.811
  lon: -83.994
  timezone: America/New_York
KFAT:
  city: Fresno
  lat: 36.7762
  lon: -119.7181
  timezone: America/Los_Angeles
KBFL:
  city: Bakersfield
  lat: 35.4336
  lon: -119.0568
  timezone: America/Los_Angeles
KSBA:
  city: Santa Barbara
  lat: 34.4262
  lon: -119.8401
  timezone: America/Los_Angeles
KGEG:
  city: Spokane
  lat: 47.6199
  lon: -117.5338
  timezone: America/Los_Angeles
# KMED:
#   city: Medford OR
#   lat: 42.3742
#   lon: -122.8735
#   timezone: America/Los_Angeles
KGJT:
  city: Grand Junction
  lat: 39.1224
  lon: -108.5267
  timezone: America/Denver
KBZN:
  city: Bozeman
  lat: 45.7775
  lon: -111.153
  timezone: America/Denver
KLAN:
  city: Lansing
  lat: 42.7787
  lon: -84.5874
  timezone: America/New_York
KRSW:
  city: Fort Myers
  lat: 26.5362
  lon: -81.7552
  timezone: America/New_York
KABI:
  city: Abilene
  lat: 32.4113
  lon: -99.6819
  timezone: America/Chicago
KMHT:
  city: Manchester NH
  lat: 42.9326
  lon: -71.4357
  timezone: America/New_York
KBGR:
  city: Bangor ME
  lat: 44.8074
  lon: -68.8281
  timezone: America/New_York
KRST:
  city: Rochester MN
  lat: 43.9083
  lon: -92.5
  timezone: America/Chicago
KLFT:
  city: Lafayette LA
  lat: 30.2053
  lon: -91.9876
  timezone: America/Chicago
KCMX:
  city: Hancock MI
  lat: 47.1684
  lon: -88.4891
  timezone: America/New_York
KRAP:
  city: Rapid City
  lat: 44.0453
  lon: -103.0574
  timezone: America/Denver
KBIS:
  city: Bismarck
  lat: 46.7727
  lon: -100.746
  timezone: America/Chicago
# KGGW:
#   city: Glasgow MT
#   lat: 48.2125
#   lon: -106.6147
#   timezone: America/Denver
KCYS:
  city: Cheyenne
  lat: 41.1557
  lon: -104.8118
  timezone: America/Denver
