#!/usr/bin/env python3
"""Peak detection backtest — predict if max °C will increase after time t.

Label: will_increase_c = 1 if the day's 24h ASOS max °C >= running_auto_max_c + 1
at sample time t. This predicts whether naive_f will shift, changing the bracket.

Sampling: 3 random from [peak-2h, peak) + 3 near peak temp + 2 from (peak, peak+1h].

Forecast proxy: rolling 7-day mean of prior daily highs (no lookahead).

Uses precompute_day_momentum() from backtest.py for efficient per-day computation.

Usage:
    cd src && python -m weather.backtest_peak
    cd src && python -m weather.backtest_peak --site KLAX,KMIA
    cd src && python -m weather.backtest_peak --loso
    cd src && python -m weather.backtest_peak --save
"""

from __future__ import annotations

import argparse
import math
import os
import pickle
import sys
from typing import Optional, List, Dict, Tuple

import numpy as np
import pandas as pd

from paths import project_path
from weather.backtest import load_site_history, precompute_day_momentum, ALL_SITES
from weather.backtest_rounding import SOLAR_NOON_CSV

DATA_DIR = project_path("data")
MODEL_PATH = project_path("data", "peak_model.pkl")
FORECAST_HIGHS_CSV = project_path("data", "forecast_highs.csv")

LABEL = "will_increase_c"


# ---------------------------------------------------------------------------
# Forecast lookup: Open-Meteo historical forecasts + rolling fallback
# ---------------------------------------------------------------------------

def load_forecast_highs() -> Dict[Tuple[str, str], float]:
    """Load per-day Open-Meteo historical forecast highs from CSV.

    Returns {(site, date_str): forecast_high_f}.
    Generated by: cd src && python -m weather.analysis --fetch-forecasts
    """
    lookup: Dict[Tuple[str, str], float] = {}
    if os.path.isfile(FORECAST_HIGHS_CSV):
        df = pd.read_csv(FORECAST_HIGHS_CSV)
        for _, row in df.iterrows():
            lookup[(row["site"], str(row["date"]))] = float(row["forecast_high_f"])
    return lookup


def build_forecast_fallback(site_df: pd.DataFrame, window: int = 7) -> Dict[str, float]:
    """Rolling 7-day mean of prior daily highs as fallback forecast proxy.

    Used only when Open-Meteo data is missing for a site-day.
    """
    daily = {}
    for date, grp in site_df.groupby("date"):
        temps = grp["temperature_f"].values.astype(float)
        if len(temps) > 0:
            daily[str(date)] = float(np.nanmax(temps))

    sorted_dates = sorted(daily.keys())
    proxy = {}
    for i, d in enumerate(sorted_dates):
        start = max(0, i - window)
        prior = [daily[sorted_dates[j]] for j in range(start, i)]
        if prior:
            proxy[d] = float(np.mean(prior))
        else:
            proxy[d] = daily[d]
    return proxy


# ---------------------------------------------------------------------------
# Feature extraction
# ---------------------------------------------------------------------------

def extract_peak_features(
    day_df: pd.DataFrame,
    precomp: dict,
    as_of_idx: int,
    solar_noon_hour: float,
    actual_max_c: float,
    forecast_high_f: float,
) -> Optional[dict]:
    """Extract features + label from one sample point within a day.

    Parameters
    ----------
    day_df : DataFrame
        Full day of observations (sorted by time).
    precomp : dict
        Output of precompute_day_momentum() for this day,
        augmented with ``_mom_df``.
    as_of_idx : int
        Index into the day's arrays — we only use data up to this point.
    solar_noon_hour : float
        Solar noon in decimal hours (e.g. 12.45).
    actual_max_c : float
        End-of-day 24h ASOS max °C (ground truth for label).
    forecast_high_f : float
        Forecast proxy: rolling 7-day mean of prior daily highs °F.
    """
    temps = precomp["temps"]
    hours = precomp["hours"]
    running_max = precomp["running_max"]
    ma_cross = precomp["ma_cross"]
    ma_short = precomp["ma_short"]
    ma_long = precomp["ma_long"]
    running_auto_max_c = precomp["running_auto_max_c"]
    n = precomp["n"]

    if as_of_idx < 2 or as_of_idx >= n:
        return None

    cur_temp = temps[as_of_idx]
    cur_hour = hours[as_of_idx]
    cur_max = running_max[as_of_idx]
    cur_max_c = running_auto_max_c[as_of_idx]

    if np.isnan(cur_temp) or np.isnan(cur_max) or np.isnan(cur_max_c):
        return None

    # --- Label ---
    will_increase = int(actual_max_c >= cur_max_c + 1)

    # --- Time features (5) ---
    ts_arr = day_df["ts"].values
    day_date = pd.Timestamp(ts_arr[0]).date()
    day_of_year = day_date.timetuple().tm_yday
    hour_decimal = cur_hour
    hours_since_solar_noon = cur_hour - solar_noon_hour
    day_of_year_sin = math.sin(2 * math.pi * day_of_year / 365.25)
    day_of_year_cos = math.cos(2 * math.pi * day_of_year / 365.25)
    pct_daylight_elapsed = max(0.0, min(1.0, (cur_hour - 6.0) / 12.0))

    # --- Temperature state (4) ---
    margin_below_max = cur_max - cur_temp
    max_indices = np.where(temps[:as_of_idx + 1] >= cur_max - 0.01)[0]
    last_max_idx = max_indices[-1] if len(max_indices) > 0 else as_of_idx
    time_since_max_hours = cur_hour - hours[last_max_idx]
    readings_since_max = as_of_idx - last_max_idx
    temp_range_so_far = cur_max - float(np.nanmin(temps[:as_of_idx + 1]))

    # --- Momentum (7) ---
    cur_ma_cross = float(ma_cross[as_of_idx]) if not np.isnan(ma_cross[as_of_idx]) else 0.0
    mom_df = precomp.get("_mom_df")
    if mom_df is not None and "rate_f_per_hr" in mom_df.columns:
        rate_val = mom_df["rate_f_per_hr"].iloc[as_of_idx]
        cur_rate = float(rate_val) if pd.notna(rate_val) else 0.0
    else:
        cur_rate = 0.0

    cur_ma_short = float(ma_short[as_of_idx]) if not np.isnan(ma_short[as_of_idx]) else cur_temp
    ma_short_minus_max = cur_ma_short - cur_max

    rate_30m_ago_idx = max(0, as_of_idx - 6)
    if mom_df is not None and "rate_f_per_hr" in mom_df.columns:
        r30 = mom_df["rate_f_per_hr"].iloc[rate_30m_ago_idx]
        rate_30m_ago = float(r30) if pd.notna(r30) else 0.0
    else:
        rate_30m_ago = 0.0
    rate_change = cur_rate - rate_30m_ago

    n_declining = 0
    for j in range(as_of_idx, last_max_idx, -1):
        if j > 0 and temps[j] < temps[j - 1]:
            n_declining += 1
        else:
            break
    max_decline_from_peak = cur_max - cur_temp

    # --- Peak shape (4) ---
    readings_at_max = int(np.sum(np.abs(temps[:as_of_idx + 1] - cur_max) < 0.01))
    at_max_indices = np.where(np.abs(temps[:as_of_idx + 1] - cur_max) < 0.01)[0]
    if len(at_max_indices) >= 2:
        time_at_max_hours = hours[at_max_indices[-1]] - hours[at_max_indices[0]]
    else:
        time_at_max_hours = 0.0
    readings_near_max_1f = int(np.sum(temps[:as_of_idx + 1] >= cur_max - 1.0))
    total_readings = as_of_idx + 1
    pct_at_or_near_max = readings_near_max_1f / total_readings if total_readings > 0 else 0.0

    # --- Trajectory (5) ---
    cur_ma_long = float(ma_long[as_of_idx]) if not np.isnan(ma_long[as_of_idx]) else cur_temp
    temp_above_ma_long = cur_temp - cur_ma_long

    def _slope_over(n_readings: int) -> float:
        start = max(0, as_of_idx - n_readings + 1)
        seg_temps = temps[start:as_of_idx + 1]
        seg_hours = hours[start:as_of_idx + 1]
        if len(seg_temps) < 2:
            return 0.0
        x = seg_hours - seg_hours[0]
        dx = x - x.mean()
        denom = np.sum(dx ** 2)
        if denom < 1e-10:
            return 0.0
        return float(np.sum(dx * (seg_temps - seg_temps.mean())) / denom)

    slope_2h = _slope_over(24)
    slope_1h = _slope_over(12)
    slope_30m = _slope_over(6)
    slope_change_2h_to_30m = slope_30m - slope_2h

    # --- Meteorological (5) ---
    wind_speed_mph = _safe_float(day_df, "wind_speed_mph", as_of_idx)
    dewpoint_f = _safe_float(day_df, "dewpoint_f", as_of_idx)
    relative_humidity_pct = _safe_float(day_df, "relative_humidity_pct", as_of_idx)
    pressure_tendency = _safe_float(day_df, "pressure_tendency", as_of_idx)
    wind_1h_ago_idx = max(0, as_of_idx - 12)
    wind_now = _safe_float(day_df, "wind_speed_mph", as_of_idx)
    wind_1h_ago = _safe_float(day_df, "wind_speed_mph", wind_1h_ago_idx)
    wind_change_1h = wind_now - wind_1h_ago

    # --- Forecast (3) ---
    forecast_gap_f = forecast_high_f - cur_max
    forecast_gap_pct = forecast_gap_f / forecast_high_f if forecast_high_f != 0 else 0.0
    current_vs_forecast = cur_temp - forecast_high_f

    return {
        # Time (5)
        "hour_decimal": round(hour_decimal, 3),
        "hours_since_solar_noon": round(hours_since_solar_noon, 3),
        "day_of_year_sin": round(day_of_year_sin, 4),
        "day_of_year_cos": round(day_of_year_cos, 4),
        "pct_daylight_elapsed": round(pct_daylight_elapsed, 4),
        # Temperature state (4)
        "margin_below_max": round(margin_below_max, 2),
        "time_since_max_hours": round(time_since_max_hours, 3),
        "readings_since_max": readings_since_max,
        "temp_range_so_far": round(temp_range_so_far, 2),
        # Momentum (7)
        "ma_cross": round(cur_ma_cross, 3),
        "rate_f_per_hr": round(cur_rate, 3),
        "ma_short_minus_max": round(ma_short_minus_max, 3),
        "rate_30m_ago": round(rate_30m_ago, 3),
        "rate_change": round(rate_change, 3),
        "n_declining_readings": n_declining,
        "max_decline_from_peak": round(max_decline_from_peak, 2),
        # Peak shape (4)
        "readings_at_max": readings_at_max,
        "time_at_max_hours": round(time_at_max_hours, 3),
        "readings_near_max_1f": readings_near_max_1f,
        "pct_at_or_near_max": round(pct_at_or_near_max, 4),
        # Trajectory (5)
        "temp_above_ma_long": round(temp_above_ma_long, 3),
        "slope_2h": round(slope_2h, 3),
        "slope_1h": round(slope_1h, 3),
        "slope_30m": round(slope_30m, 3),
        "slope_change_2h_to_30m": round(slope_change_2h_to_30m, 3),
        # Meteorological (5)
        "wind_speed_mph": round(wind_speed_mph, 2),
        "dewpoint_f": round(dewpoint_f, 2),
        "relative_humidity_pct": round(relative_humidity_pct, 2),
        "pressure_tendency": round(pressure_tendency, 3),
        "wind_change_1h": round(wind_change_1h, 2),
        # Forecast (3)
        "forecast_gap_f": round(forecast_gap_f, 2),
        "forecast_gap_pct": round(forecast_gap_pct, 4),
        "current_vs_forecast": round(current_vs_forecast, 2),
        # Label
        LABEL: will_increase,
    }


def _safe_float(df: pd.DataFrame, col: str, idx: int) -> float:
    """Get a float value from a DataFrame column at index, defaulting to 0."""
    if col not in df.columns:
        return 0.0
    val = df[col].iloc[idx]
    if pd.isna(val):
        return 0.0
    return float(val)


FEATURE_COLS = [
    # Time (5)
    "hour_decimal", "hours_since_solar_noon",
    "day_of_year_sin", "day_of_year_cos", "pct_daylight_elapsed",
    # Temperature state (4)
    "margin_below_max", "time_since_max_hours", "readings_since_max",
    "temp_range_so_far",
    # Momentum (7)
    "ma_cross", "rate_f_per_hr", "ma_short_minus_max",
    "rate_30m_ago", "rate_change", "n_declining_readings",
    "max_decline_from_peak",
    # Peak shape (4)
    "readings_at_max", "time_at_max_hours", "readings_near_max_1f",
    "pct_at_or_near_max",
    # Trajectory (5)
    "temp_above_ma_long", "slope_2h", "slope_1h", "slope_30m",
    "slope_change_2h_to_30m",
    # Meteorological (5)
    "wind_speed_mph", "dewpoint_f", "relative_humidity_pct",
    "pressure_tendency", "wind_change_1h",
    # Forecast (3)
    "forecast_gap_f", "forecast_gap_pct", "current_vs_forecast",
]


# ---------------------------------------------------------------------------
# Day sampling
# ---------------------------------------------------------------------------

def _compute_actual_max_c(day_df: pd.DataFrame) -> Optional[float]:
    """End-of-day ground truth max °C: prefer 24h ASOS, fall back to max(temp_c)."""
    if "max_temp_24h_c" in day_df.columns:
        val = pd.to_numeric(day_df["max_temp_24h_c"], errors="coerce").max()
        if not np.isnan(val):
            return float(val)
    if "temperature_c" in day_df.columns:
        val = pd.to_numeric(day_df["temperature_c"], errors="coerce").max()
        if not np.isnan(val):
            return float(val)
    return None


def generate_day_samples(
    site: str,
    day_df: pd.DataFrame,
    precomp: dict,
    solar_noon_hour: float,
    actual_max_c: float,
    forecast_high_f: float,
    rng: np.random.RandomState,
) -> List[dict]:
    """3 random from [peak-2h, peak-~0], 3 near peak temp, 2 from [peak, peak+1h]."""
    hours = precomp["hours"]
    temps = precomp["temps"]
    running_max = precomp["running_max"]
    peak_hour = precomp["peak_hour"]
    samples = []

    def _sample(indices: np.ndarray, k: int) -> List[int]:
        if len(indices) <= k:
            return list(indices)
        return list(rng.choice(indices, size=k, replace=False))

    # 1) 3 random points from [peak-2h, peak) — approaching peak
    pre_mask = (hours >= peak_hour - 2.0) & (hours < peak_hour)
    pre_indices = np.where(pre_mask)[0]

    # 2) 3 points near peak temp (within 1°F of running max at that time)
    peak_temp = running_max[-1]  # final running max = daily high
    near_mask = (np.abs(temps - peak_temp) <= 1.0) & (hours >= peak_hour - 1.0) & (hours <= peak_hour + 1.0)
    near_indices = np.where(near_mask)[0]

    # 3) 2 random points from (peak, peak+1h] — just after peak
    post_mask = (hours > peak_hour) & (hours <= peak_hour + 1.0)
    post_indices = np.where(post_mask)[0]

    chosen = _sample(pre_indices, 3) + _sample(near_indices, 3) + _sample(post_indices, 2)

    for idx in chosen:
        feat = extract_peak_features(
            day_df, precomp, idx, solar_noon_hour, actual_max_c, forecast_high_f)
        if feat is not None:
            feat["site"] = site
            feat["date"] = str(day_df["date"].iloc[0])
            samples.append(feat)

    return samples


# ---------------------------------------------------------------------------
# Load all samples
# ---------------------------------------------------------------------------

def load_all_samples(sites: Optional[List[str]] = None) -> pd.DataFrame:
    """Load all sites, precompute momentum, generate samples."""
    from weather.prediction import compute_momentum

    if sites is None:
        sites = list(ALL_SITES)

    # Load solar noon cache
    solar_noon_lookup: Dict[Tuple[str, str], float] = {}
    if os.path.isfile(SOLAR_NOON_CSV):
        sn_df = pd.read_csv(SOLAR_NOON_CSV)
        for _, row in sn_df.iterrows():
            solar_noon_lookup[(row["site"], str(row["date"]))] = float(row["solar_noon_hour"])
        print(f"  Loaded {len(solar_noon_lookup)} solar noon entries")
    else:
        print(f"  No solar noon cache — using fallback (12.0)")

    # Load Open-Meteo historical forecast highs
    forecast_lookup = load_forecast_highs()
    n_forecast = len(forecast_lookup)
    if n_forecast:
        print(f"  Loaded {n_forecast} Open-Meteo forecast entries")
    else:
        print(f"  No Open-Meteo forecasts — using rolling 7-day fallback")

    rng = np.random.RandomState(42)
    all_rows: List[dict] = []
    total_days = 0
    skipped = 0
    n_forecast_hits = 0
    n_fallback = 0

    for site in sites:
        df = load_site_history(site)
        if df.empty:
            print(f"  {site}: no data")
            continue

        # Build rolling fallback for dates missing from Open-Meteo
        forecast_fallback = build_forecast_fallback(df)

        site_days = 0
        for date, day_df in df.groupby("date"):
            if len(day_df) < 200:
                skipped += 1
                continue
            day_df = day_df.sort_values("ts").reset_index(drop=True)

            actual_max_c = _compute_actual_max_c(day_df)
            if actual_max_c is None:
                skipped += 1
                continue

            date_str = str(date)
            om_val = forecast_lookup.get((site, date_str))
            if om_val is not None:
                forecast_high_f = om_val
                n_forecast_hits += 1
            else:
                forecast_high_f = forecast_fallback.get(date_str, 70.0)
                n_fallback += 1

            precomp = precompute_day_momentum(day_df)
            mom_df = compute_momentum(day_df)
            precomp["_mom_df"] = mom_df

            sn = solar_noon_lookup.get((site, str(date)), 12.0)
            samples = generate_day_samples(
                site, day_df, precomp, sn, actual_max_c, forecast_high_f, rng)
            all_rows.extend(samples)
            site_days += 1

        total_days += site_days
        print(f"  {site}: {site_days} days, {len(all_rows)} total samples so far")
        sys.stdout.flush()

    print(f"  Total: {total_days} days, {len(all_rows)} samples "
          f"({skipped} days skipped)")
    print(f"  Forecast source: {n_forecast_hits} Open-Meteo, {n_fallback} rolling fallback")

    if not all_rows:
        return pd.DataFrame()
    return pd.DataFrame(all_rows)


# ---------------------------------------------------------------------------
# Training and evaluation
# ---------------------------------------------------------------------------

def _build_models() -> list:
    """Return list of (name, model) tuples to sweep."""
    from sklearn.ensemble import (
        GradientBoostingClassifier, RandomForestClassifier,
        AdaBoostClassifier,
    )
    from sklearn.linear_model import LogisticRegression
    from sklearn.tree import DecisionTreeClassifier

    return [
        ("GBM", GradientBoostingClassifier(
            n_estimators=200, max_depth=4, learning_rate=0.1,
            min_samples_leaf=5, random_state=42)),
        ("GBM-deep", GradientBoostingClassifier(
            n_estimators=300, max_depth=6, learning_rate=0.05,
            min_samples_leaf=10, random_state=42)),
        ("RandomForest", RandomForestClassifier(
            n_estimators=200, max_depth=8, min_samples_leaf=5,
            random_state=42, n_jobs=-1)),
        ("LogisticRegression", LogisticRegression(
            max_iter=1000, random_state=42)),
        ("AdaBoost", AdaBoostClassifier(
            n_estimators=100, learning_rate=0.1, random_state=42)),
        ("DecisionTree", DecisionTreeClassifier(
            max_depth=6, min_samples_leaf=10, random_state=42)),
    ]


def train_and_evaluate(df: pd.DataFrame) -> dict:
    """Leave-one-site-out CV with model sweep.

    For each model, runs LOSO CV across all sites, collecting per-site
    accuracy and F1. Prints a comparison table and detailed results for
    the best model.
    """
    from sklearn.metrics import (
        accuracy_score, precision_score, recall_score, f1_score,
        classification_report,
    )
    from sklearn.preprocessing import StandardScaler

    sites = sorted(df["site"].unique())
    models = _build_models()

    print(f"\n{'=' * 70}")
    print(f"  LEAVE-ONE-SITE-OUT CV — MODEL SWEEP ({len(sites)} sites)")
    print(f"{'=' * 70}")

    # Majority-class baseline
    pos_rate = df[LABEL].mean()
    baseline_acc = max(pos_rate, 1 - pos_rate)
    baseline_label = "always-0" if pos_rate < 0.5 else "always-1"
    print(f"  Baseline ({baseline_label}): {baseline_acc:.1%}\n")

    # Store per-model LOSO results
    model_results = {}

    for model_name, model_template in models:
        needs_scaling = model_name == "LogisticRegression"
        all_y_true = []
        all_y_pred = []
        all_y_prob = []
        all_sites_list = []
        per_site = []

        for test_site in sites:
            train_df = df[df["site"] != test_site]
            test_df = df[df["site"] == test_site]
            if len(test_df) < 10:
                continue

            X_train = train_df[FEATURE_COLS].values.copy()
            y_train = train_df[LABEL].values
            X_test = test_df[FEATURE_COLS].values.copy()
            y_test = test_df[LABEL].values

            if needs_scaling:
                scaler = StandardScaler()
                X_train = scaler.fit_transform(X_train)
                X_test = scaler.transform(X_test)

            # Clone model for each fold
            from sklearn.base import clone
            model = clone(model_template)
            model.fit(X_train, y_train)
            y_pred = model.predict(X_test)

            if hasattr(model, "predict_proba"):
                y_prob = model.predict_proba(X_test)[:, 1]
            else:
                y_prob = y_pred.astype(float)

            acc = accuracy_score(y_test, y_pred)
            f1 = f1_score(y_test, y_pred, zero_division=0)

            per_site.append({
                "site": test_site,
                "n_test": len(test_df),
                "accuracy": acc,
                "f1": f1,
                "pos_pct": float(y_test.mean()),
            })

            all_y_true.extend(y_test)
            all_y_pred.extend(y_pred)
            all_y_prob.extend(y_prob)
            all_sites_list.extend([test_site] * len(y_test))

        all_y_true = np.array(all_y_true)
        all_y_pred = np.array(all_y_pred)
        all_y_prob = np.array(all_y_prob)

        overall_acc = accuracy_score(all_y_true, all_y_pred)
        overall_f1 = f1_score(all_y_true, all_y_pred, zero_division=0)
        overall_prec = precision_score(all_y_true, all_y_pred, zero_division=0)
        overall_rec = recall_score(all_y_true, all_y_pred, zero_division=0)

        model_results[model_name] = {
            "per_site": per_site,
            "accuracy": overall_acc,
            "f1": overall_f1,
            "precision": overall_prec,
            "recall": overall_rec,
            "y_true": all_y_true,
            "y_pred": all_y_pred,
            "y_prob": all_y_prob,
            "sites": all_sites_list,
        }

    # --- Model comparison table ---
    print(f"  {'Model':<22s} {'Acc':>7s} {'Prec':>7s} {'Rec':>7s} {'F1':>7s}")
    print(f"  {'-'*22} {'-'*7} {'-'*7} {'-'*7} {'-'*7}")
    print(f"  {baseline_label:<22s} {baseline_acc:>7.4f} {'—':>7s} {'—':>7s} {'—':>7s}")

    best_name = None
    best_f1 = -1.0
    for name in [n for n, _ in models]:
        r = model_results[name]
        tag = ""
        if r["f1"] > best_f1:
            best_f1 = r["f1"]
            best_name = name
        print(f"  {name:<22s} {r['accuracy']:>7.4f} {r['precision']:>7.4f} "
              f"{r['recall']:>7.4f} {r['f1']:>7.4f}")

    print(f"\n  Best model: {best_name} (F1={best_f1:.4f})")

    # --- Detailed results for best model ---
    best = model_results[best_name]

    print(f"\n{'=' * 70}")
    print(f"  {best_name} — DETAILED RESULTS")
    print(f"{'=' * 70}")
    print(classification_report(
        best["y_true"], best["y_pred"],
        target_names=["no_increase", "will_increase"]))

    # Per-site breakdown
    print(f"  PER-SITE ACCURACY")
    print(f"  {'Site':<6} {'N':>6} {'Acc':>7} {'F1':>7} {'Pos%':>7}")
    print(f"  {'-'*6} {'-'*6} {'-'*7} {'-'*7} {'-'*7}")
    for ps in best["per_site"]:
        print(f"  {ps['site']:<6} {ps['n_test']:>6} {ps['accuracy']:>7.4f} "
              f"{ps['f1']:>7.4f} {ps['pos_pct']:>6.1%}")

    accs = [ps["accuracy"] for ps in best["per_site"]]
    f1s = [ps["f1"] for ps in best["per_site"]]
    print(f"\n  Mean accuracy: {np.mean(accs):.4f} ± {np.std(accs):.4f}")
    print(f"  Mean F1:       {np.mean(f1s):.4f} ± {np.std(f1s):.4f}")

    # Feature importances — train best model on full data
    from sklearn.base import clone
    full_model = clone(model_results[best_name].get("_template", _build_models()[0][1]))
    # Find the template
    for name, tmpl in _build_models():
        if name == best_name:
            full_model = clone(tmpl)
            break
    X_all = df[FEATURE_COLS].values
    y_all = df[LABEL].values
    full_model.fit(X_all, y_all)
    if hasattr(full_model, "feature_importances_"):
        _print_feature_importances(full_model, FEATURE_COLS)

    # Calibration
    _print_calibration(best["y_true"], best["y_prob"])

    return {
        "model_name": best_name,
        "model": full_model,
        "accuracy": best["accuracy"],
        "f1": best["f1"],
        "per_site": best["per_site"],
        "all_results": {k: {
            "accuracy": v["accuracy"], "f1": v["f1"],
            "precision": v["precision"], "recall": v["recall"],
        } for k, v in model_results.items()},
    }


# ---------------------------------------------------------------------------
# Analysis helpers
# ---------------------------------------------------------------------------

def _print_feature_importances(model, feature_cols: list, top_n: int = 15) -> None:
    importances = model.feature_importances_
    indices = np.argsort(importances)[::-1]

    print(f"\n  TOP {top_n} FEATURE IMPORTANCES")
    print(f"  {'-' * 40}")
    for rank, idx in enumerate(indices[:top_n], 1):
        print(f"  {rank:>2}. {feature_cols[idx]:<30s} {importances[idx]:.4f}")


def _print_per_site_accuracy(test_df: pd.DataFrame, y_pred: np.ndarray) -> None:
    meta = test_df.copy().reset_index(drop=True)
    meta["y_pred"] = y_pred

    print(f"\n  PER-SITE ACCURACY")
    print(f"  {'Site':<6} {'N':>6} {'Acc':>7} {'Pos%':>7}")
    print(f"  {'-'*6} {'-'*6} {'-'*7} {'-'*7}")

    for site in sorted(meta["site"].unique()):
        site_mask = meta["site"] == site
        site_df = meta[site_mask]
        y_t = site_df[LABEL].values
        y_p = site_df["y_pred"].values
        acc = (y_t == y_p).mean()
        pos = y_t.mean()
        print(f"  {site:<6} {len(site_df):>6} {acc:>7.4f} {pos:>6.1%}")


def _print_calibration(y_true: np.ndarray, y_prob: np.ndarray, n_bins: int = 10) -> None:
    print(f"\n  CALIBRATION TABLE ({n_bins} bins)")
    print(f"  {'Bin':>12s} {'Count':>7} {'Mean pred':>10} {'Mean actual':>12} {'Gap':>7}")
    print(f"  {'-'*12} {'-'*7} {'-'*10} {'-'*12} {'-'*7}")

    bin_edges = np.linspace(0, 1, n_bins + 1)
    for i in range(n_bins):
        lo, hi = bin_edges[i], bin_edges[i + 1]
        mask = (y_prob >= lo) & (y_prob < hi) if i < n_bins - 1 else (y_prob >= lo) & (y_prob <= hi)
        count = mask.sum()
        if count == 0:
            continue
        mean_pred = y_prob[mask].mean()
        mean_actual = y_true[mask].mean()
        gap = mean_pred - mean_actual
        print(f"  [{lo:.1f}, {hi:.1f}) {count:>7} {mean_pred:>10.4f} {mean_actual:>12.4f} {gap:>+7.4f}")


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def main() -> None:
    parser = argparse.ArgumentParser(description="Peak detection backtest")
    parser.add_argument("--site", type=str, default=None,
                        help="Comma-separated ICAO codes (default: all)")
    parser.add_argument("--save", action="store_true",
                        help="Persist trained model to disk")
    args = parser.parse_args()

    sites = args.site.split(",") if args.site else None

    print("=" * 70)
    print("  PEAK DETECTION BACKTEST")
    print(f"  Label: {LABEL} = 1 if 24h ASOS max °C >= running_auto_max_c + 1")
    print(f"  Split: Leave-one-site-out CV")
    print(f"  Sampling: 3 pre-peak + 3 near peak temp + 2 post-peak")
    print(f"  Forecast: Open-Meteo historical highs (fallback: rolling 7-day mean)")
    print("=" * 70)
    print()

    print("Loading and generating samples...")
    df = load_all_samples(sites)
    if df.empty:
        print("No samples generated. Check data files.")
        sys.exit(1)

    n_sites = df["site"].nunique()
    n_days = df.groupby(["site", "date"]).ngroups
    n_pos = (df[LABEL] == 1).sum()
    n_neg = (df[LABEL] == 0).sum()
    print(f"\n  Dataset: {len(df)} samples, {n_days} site-days, {n_sites} sites")
    print(f"  Class balance: {n_pos} positive ({n_pos / len(df):.1%}), "
          f"{n_neg} negative ({n_neg / len(df):.1%})")

    results = train_and_evaluate(df)

    if args.save:
        model = results.get("model")
        if model is not None:
            with open(MODEL_PATH, "wb") as f:
                pickle.dump({"model": model, "features": FEATURE_COLS}, f)
            print(f"\n  Model saved to {MODEL_PATH}")

    print("\nDone.")


if __name__ == "__main__":
    main()
