#!/usr/bin/env python3
"""Peak detection backtest — predict if naive_f will shift +1 after time t.

Label: will_increase_f = 1 if round(actual_max_c * 9/5 + 32) >= round(running_auto_max_c * 9/5 + 32) + 1
at sample time t. Predicts whether the settlement °F bracket will shift up.

Sampling: 3 random from [peak-2h, peak) + 3 near peak temp + 2 from (peak, peak+1h].

Forecast proxy: rolling 7-day mean of prior daily highs (no lookahead).

Uses precompute_day_momentum() from backtest.py for efficient per-day computation.

Usage:
    cd src && python -m weather.backtest_peak
    cd src && python -m weather.backtest_peak --site KLAX,KMIA
    cd src && python -m weather.backtest_peak --loso
    cd src && python -m weather.backtest_peak --save
"""

from __future__ import annotations

import argparse
import math
import os
import pickle
import sys
from typing import Optional, List, Dict, Tuple

import numpy as np
import pandas as pd

from paths import project_path
from weather.backtest import load_site_history, precompute_day_momentum, ALL_SITES
from weather.backtest_rounding import ALL_SITES_WITH_TRAINING
from weather.backtest_rounding import SOLAR_NOON_CSV

DATA_DIR = project_path("data", "weather")
MODEL_DIR = project_path("models", "peak_model")
MODEL_PATH = os.path.join(MODEL_DIR, "model.pkl")
FORECAST_HIGHS_CSV = project_path("data", "weather", "forecast_highs.csv")
FORECAST_HOURLY_CSV = project_path("data", "weather", "forecast_hourly.csv")

LABEL = "will_increase_f"


# ---------------------------------------------------------------------------
# Forecast lookup: Open-Meteo historical forecasts + rolling fallback
# ---------------------------------------------------------------------------

def load_forecast_highs() -> Dict[Tuple[str, str], float]:
    """Load per-day Open-Meteo historical forecast highs from CSV.

    Returns {(site, date_str): forecast_high_f}.
    Generated by: cd src && python -m weather.analysis --fetch-forecasts
    """
    lookup: Dict[Tuple[str, str], float] = {}
    if os.path.isfile(FORECAST_HIGHS_CSV):
        df = pd.read_csv(FORECAST_HIGHS_CSV)
        for _, row in df.iterrows():
            lookup[(row["site"], str(row["date"]))] = float(row["forecast_high_f"])
    return lookup


def load_forecast_hourly() -> Dict[Tuple[str, str], List[Tuple[int, float]]]:
    """Load hourly Open-Meteo historical forecasts from CSV.

    Returns {(site, date_str): [(hour, temp_f), ...]}.
    Generated by: cd src && python -m weather.analysis --fetch-hourly-forecasts
    """
    lookup: Dict[Tuple[str, str], List[Tuple[int, float]]] = {}
    if os.path.isfile(FORECAST_HOURLY_CSV):
        df = pd.read_csv(FORECAST_HOURLY_CSV)
        for (site, date), grp in df.groupby(["site", "date"]):
            hours_temps = sorted(zip(grp["hour"].astype(int), grp["temperature_f"].astype(float)))
            lookup[(site, str(date))] = hours_temps
    return lookup


def build_forecast_fallback(site_df: pd.DataFrame, window: int = 7) -> Dict[str, float]:
    """Rolling 7-day mean of prior daily highs as fallback forecast proxy.

    Used only when Open-Meteo data is missing for a site-day.
    """
    daily = {}
    for date, grp in site_df.groupby("date"):
        temps = grp["temperature_f"].values.astype(float)
        if len(temps) > 0:
            daily[str(date)] = float(np.nanmax(temps))

    sorted_dates = sorted(daily.keys())
    proxy = {}
    for i, d in enumerate(sorted_dates):
        start = max(0, i - window)
        prior = [daily[sorted_dates[j]] for j in range(start, i)]
        if prior:
            proxy[d] = float(np.mean(prior))
        else:
            proxy[d] = daily[d]
    return proxy


# ---------------------------------------------------------------------------
# Feature extraction
# ---------------------------------------------------------------------------

def extract_peak_features(
    day_df: pd.DataFrame,
    precomp: dict,
    as_of_idx: int,
    solar_noon_hour: float,
    actual_max_c: float,
    forecast_high_f: float,
    forecast_hourly: Optional[List[Tuple[int, float]]] = None,
    yesterday: Optional[dict] = None,
) -> Optional[dict]:
    """Extract features + label from one sample point within a day.

    Parameters
    ----------
    day_df : DataFrame
        Full day of observations (sorted by time).
    precomp : dict
        Output of precompute_day_momentum() for this day,
        augmented with ``_mom_df``.
    as_of_idx : int
        Index into the day's arrays — we only use data up to this point.
    solar_noon_hour : float
        Solar noon in decimal hours (e.g. 12.45).
    actual_max_c : float
        End-of-day 24h ASOS max °C (ground truth — converted to °F for label).
    forecast_high_f : float
        Forecast proxy: rolling 7-day mean of prior daily highs °F.
    forecast_hourly : list of (hour, temp_f), optional
        Hourly forecast curve for this day from Open-Meteo.
    """
    temps = precomp["temps"]
    hours = precomp["hours"]
    running_max = precomp["running_max"]
    ma_cross = precomp["ma_cross"]
    ma_short = precomp["ma_short"]
    ma_long = precomp["ma_long"]
    running_auto_max_c = precomp["running_auto_max_c"]
    n = precomp["n"]

    if as_of_idx < 2 or as_of_idx >= n:
        return None

    cur_temp = temps[as_of_idx]
    cur_hour = hours[as_of_idx]
    cur_max = running_max[as_of_idx]
    cur_max_c = running_auto_max_c[as_of_idx]

    if np.isnan(cur_temp) or np.isnan(cur_max) or np.isnan(cur_max_c):
        return None

    # --- Label ---
    # Compare rounded °F: does the final settlement °F end up ≥ current naive_f + 1?
    cur_f_float = cur_max_c * 9.0 / 5.0 + 32.0
    cur_naive_f = round(cur_f_float)
    actual_naive_f = round(actual_max_c * 9.0 / 5.0 + 32.0)
    will_increase = int(actual_naive_f >= cur_naive_f + 1)
    will_increase_2 = int(actual_naive_f >= cur_naive_f + 2)
    will_not_decrease = int(actual_naive_f >= cur_naive_f)

    # --- Rounding features (3) ---
    # How close cur_max_c is to the next °F flip (0 = right on boundary, 0.5 = far)
    frac = cur_f_float % 1.0
    boundary_distance = min(frac, 1.0 - frac)
    # How many distinct °F values map to this whole °C?
    from weather.prediction import c_to_possible_f
    n_possible_f = len(c_to_possible_f(int(cur_max_c)))
    # Fractional part of C→F conversion (asymmetric: high frac = closer to rounding up)
    cur_f_fractional = frac

    # --- METAR features (5) ---
    # Computed from running METAR max at the sample point
    running_metar_max_c = precomp["running_metar_max_c"]
    cur_metar_max_c = running_metar_max_c[as_of_idx]
    _max_c_int = int(cur_max_c)
    _possible_f = c_to_possible_f(_max_c_int)

    if not np.isnan(cur_metar_max_c) and (cur_metar_max_c >= cur_max_c - 2.0):
        # Only use METAR when it's near the auto peak (within 2°C).
        # Morning METARs far below the peak are noise, not signal.
        has_metar = 1.0
        metar_gap_c = cur_metar_max_c - cur_max_c  # positive = METAR above auto
        metar_confirm = min(max(metar_gap_c, 0.0), 1.0)  # clamped [0, 1]
        if len(_possible_f) == 2:
            boundary_c = (_possible_f[0] + 0.5 - 32) * 5.0 / 9.0
            metar_above_boundary = 1.0 if cur_metar_max_c > boundary_c else 0.0
            metar_boundary_margin_c = cur_metar_max_c - boundary_c
        else:
            metar_above_boundary = 0.0
            metar_boundary_margin_c = 0.0
    else:
        has_metar = 0.0
        metar_gap_c = 0.0
        metar_confirm = 0.0
        metar_above_boundary = 0.0
        metar_boundary_margin_c = 0.0

    # --- Time features (5) ---
    ts_arr = day_df["ts"].values
    day_date = pd.Timestamp(ts_arr[0]).date()
    day_of_year = day_date.timetuple().tm_yday
    hour_decimal = cur_hour
    hours_since_solar_noon = cur_hour - solar_noon_hour
    day_of_year_sin = math.sin(2 * math.pi * day_of_year / 365.25)
    day_of_year_cos = math.cos(2 * math.pi * day_of_year / 365.25)
    pct_daylight_elapsed = max(0.0, min(1.0, (cur_hour - 6.0) / 12.0))

    # --- Temperature state (4) ---
    margin_below_max = cur_max - cur_temp
    max_indices = np.where(temps[:as_of_idx + 1] >= cur_max - 0.01)[0]
    last_max_idx = max_indices[-1] if len(max_indices) > 0 else as_of_idx
    time_since_max_hours = cur_hour - hours[last_max_idx]
    readings_since_max = as_of_idx - last_max_idx
    temp_range_so_far = cur_max - float(np.nanmin(temps[:as_of_idx + 1]))

    # --- Momentum (7) ---
    cur_ma_cross = float(ma_cross[as_of_idx]) if not np.isnan(ma_cross[as_of_idx]) else 0.0
    mom_df = precomp.get("_mom_df")
    if mom_df is not None and "rate_f_per_hr" in mom_df.columns:
        rate_val = mom_df["rate_f_per_hr"].iloc[as_of_idx]
        cur_rate = float(rate_val) if pd.notna(rate_val) else 0.0
    else:
        cur_rate = 0.0

    cur_ma_short = float(ma_short[as_of_idx]) if not np.isnan(ma_short[as_of_idx]) else cur_temp
    ma_short_minus_max = cur_ma_short - cur_max

    def _rate_at(offset_readings: int) -> float:
        idx = max(0, as_of_idx - offset_readings)
        if mom_df is not None and "rate_f_per_hr" in mom_df.columns:
            v = mom_df["rate_f_per_hr"].iloc[idx]
            return float(v) if pd.notna(v) else 0.0
        return 0.0

    rate_30m_ago = _rate_at(6)
    rate_1h_ago = _rate_at(12)
    rate_2h_ago = _rate_at(24)
    rate_change = cur_rate - rate_30m_ago

    # Second derivatives (acceleration): how is the rate itself changing?
    accel_30m = cur_rate - rate_30m_ago              # °F/hr² over 30m
    accel_1h = cur_rate - rate_1h_ago                # °F/hr² over 1h
    accel_2h = cur_rate - rate_2h_ago                # °F/hr² over 2h
    accel_change = accel_30m - (rate_30m_ago - rate_1h_ago)  # jerk: is accel itself changing?

    n_declining = 0
    for j in range(as_of_idx, last_max_idx, -1):
        if j > 0 and temps[j] < temps[j - 1]:
            n_declining += 1
        else:
            break
    max_decline_from_peak = cur_max - cur_temp

    # Composite decline score: 0 = no evidence of decline, 1 = strong decline
    # Combines: negative rate, negative MA cross, drop from peak, consecutive declines
    _decline_signals = 0.0
    _decline_count = 0
    if cur_rate < -1.0:          # cooling > 1°F/hr
        _decline_signals += min(abs(cur_rate) / 5.0, 1.0)
        _decline_count += 1
    if cur_ma_cross < -0.5:      # MA cross negative
        _decline_signals += min(abs(cur_ma_cross) / 3.0, 1.0)
        _decline_count += 1
    if max_decline_from_peak > 1.0:  # dropped > 1°F from peak
        _decline_signals += min(max_decline_from_peak / 5.0, 1.0)
        _decline_count += 1
    if n_declining >= 3:         # 3+ consecutive declining readings
        _decline_signals += min(n_declining / 10.0, 1.0)
        _decline_count += 1
    decline_confidence = _decline_signals / max(_decline_count, 1)

    # --- Peak shape (4) ---
    readings_at_max = int(np.sum(np.abs(temps[:as_of_idx + 1] - cur_max) < 0.01))
    at_max_indices = np.where(np.abs(temps[:as_of_idx + 1] - cur_max) < 0.01)[0]
    if len(at_max_indices) >= 2:
        time_at_max_hours = hours[at_max_indices[-1]] - hours[at_max_indices[0]]
    else:
        time_at_max_hours = 0.0
    readings_near_max_1f = int(np.sum(temps[:as_of_idx + 1] >= cur_max - 1.0))
    total_readings = as_of_idx + 1
    pct_at_or_near_max = readings_near_max_1f / total_readings if total_readings > 0 else 0.0

    # --- Trajectory (5) ---
    cur_ma_long = float(ma_long[as_of_idx]) if not np.isnan(ma_long[as_of_idx]) else cur_temp
    temp_above_ma_long = cur_temp - cur_ma_long

    def _slope_over(n_readings: int) -> float:
        start = max(0, as_of_idx - n_readings + 1)
        seg_temps = temps[start:as_of_idx + 1]
        seg_hours = hours[start:as_of_idx + 1]
        if len(seg_temps) < 2:
            return 0.0
        x = seg_hours - seg_hours[0]
        dx = x - x.mean()
        denom = np.sum(dx ** 2)
        if denom < 1e-10:
            return 0.0
        return float(np.sum(dx * (seg_temps - seg_temps.mean())) / denom)

    slope_2h = _slope_over(24)
    slope_1h = _slope_over(12)
    slope_30m = _slope_over(6)
    slope_change_2h_to_30m = slope_30m - slope_2h

    # --- Meteorological (5) ---
    wind_speed_mph = _safe_float(day_df, "wind_speed_mph", as_of_idx)
    dewpoint_f = _safe_float(day_df, "dewpoint_f", as_of_idx)
    relative_humidity_pct = _safe_float(day_df, "relative_humidity_pct", as_of_idx)
    pressure_tendency = _safe_float(day_df, "pressure_tendency", as_of_idx)
    wind_1h_ago_idx = max(0, as_of_idx - 12)
    wind_now = _safe_float(day_df, "wind_speed_mph", as_of_idx)
    wind_1h_ago = _safe_float(day_df, "wind_speed_mph", wind_1h_ago_idx)
    wind_change_1h = wind_now - wind_1h_ago

    # --- Forecast daily (3) ---
    forecast_gap_f = forecast_high_f - cur_max
    forecast_gap_pct = forecast_gap_f / forecast_high_f if forecast_high_f != 0 else 0.0
    current_vs_forecast = cur_temp - forecast_high_f

    # --- Forecast curve (7) ---
    # Derived from hourly Open-Meteo historical forecast
    fcst_hours_since_peak = 0.0
    fcst_peak_hour = 14.0  # fallback
    fcst_remaining_vs_cur = 0.0
    fcst_near_peak_1f = 0
    fcst_near_peak_2f = 0
    fcst_slope_at_t = 0.0
    fcst_accel_at_t = 0.0
    fcst_plateau_hours = 0

    # --- Forecast derivative profile (6) ---
    fcst_d1_at_peak = 0.0       # slope at forecast peak hour (should be ~0)
    fcst_d1_max = 0.0           # steepest rise (max positive slope)
    fcst_d1_min = 0.0           # steepest decline (max negative slope)
    fcst_d2_at_peak = 0.0       # curvature at peak (how sharp the rollover is)
    fcst_d2_min = 0.0           # most concave-down point
    fcst_d1_post_mean = 0.0     # mean slope in hours after forecast peak

    # --- Forecast tracking accuracy (4) ---
    fcst_tracking_bias = 0.0    # mean(obs - forecast) for hours up to now
    fcst_tracking_rmse = 0.0    # RMSE of obs vs forecast so far
    fcst_tracking_max_err = 0.0 # worst |obs - forecast| deviation so far
    fcst_obs_above_pct = 0.5    # fraction of matched hours where obs > forecast
    fcst_tracking_bias_1h = 0.0 # mean(obs - forecast) for the last hour only
    fcst_tracking_rmse_1h = 0.0 # RMSE for the last hour only

    if forecast_hourly and len(forecast_hourly) >= 6:
        fh_hours = np.array([h for h, _ in forecast_hourly], dtype=float)
        fh_temps = np.array([t for _, t in forecast_hourly], dtype=float)
        fcst_peak_idx = int(np.argmax(fh_temps))
        fcst_peak_temp = fh_temps[fcst_peak_idx]
        fcst_peak_hour = fh_hours[fcst_peak_idx]
        fcst_hours_since_peak = cur_hour - fcst_peak_hour

        # Forecast remaining max: highest forecast temp from current hour onward
        future_mask = fh_hours >= cur_hour
        fcst_remaining_max = float(fh_temps[future_mask].max()) if future_mask.any() else float(fh_temps[-1])
        fcst_remaining_vs_cur = fcst_remaining_max - cur_max

        # Hours within 1°F / 2°F of forecast peak
        fcst_near_peak_1f = int(np.sum(np.abs(fh_temps - fcst_peak_temp) <= 1.0))
        fcst_near_peak_2f = int(np.sum(np.abs(fh_temps - fcst_peak_temp) <= 2.0))

        # Plateau: consecutive hours within 1°F of peak around peak hour
        fcst_plateau_hours = 1
        for j in range(fcst_peak_idx + 1, len(fh_temps)):
            if abs(fh_temps[j] - fcst_peak_temp) <= 1.0:
                fcst_plateau_hours += 1
            else:
                break
        for j in range(fcst_peak_idx - 1, -1, -1):
            if abs(fh_temps[j] - fcst_peak_temp) <= 1.0:
                fcst_plateau_hours += 1
            else:
                break

        # First derivative (°F/hr) at each forecast hour
        fh_d1 = np.diff(fh_temps)  # len = len(fh_temps) - 1
        fcst_d1_max = float(np.max(fh_d1))
        fcst_d1_min = float(np.min(fh_d1))
        if 0 < fcst_peak_idx < len(fh_d1):
            fcst_d1_at_peak = float(fh_d1[fcst_peak_idx - 1])
        elif fcst_peak_idx < len(fh_d1):
            fcst_d1_at_peak = float(fh_d1[fcst_peak_idx])

        # Mean slope after forecast peak (anticipated decline rate)
        post_d1 = fh_d1[fcst_peak_idx:]
        if len(post_d1) > 0:
            fcst_d1_post_mean = float(np.mean(post_d1))

        # Second derivative (°F/hr²) — curvature
        if len(fh_d1) >= 2:
            fh_d2 = np.diff(fh_d1)
            fcst_d2_min = float(np.min(fh_d2))
            # d2 at peak: index shifted by 1 from d1
            d2_peak_idx = max(0, fcst_peak_idx - 1)
            if d2_peak_idx < len(fh_d2):
                fcst_d2_at_peak = float(fh_d2[d2_peak_idx])

        # Forecast slope & acceleration at current hour (interpolated)
        cur_h_int = int(cur_hour)
        if 1 <= cur_h_int < len(fh_temps) - 1:
            # Find the matching index in forecast hours
            h_idx = np.searchsorted(fh_hours, cur_h_int)
            if 1 <= h_idx < len(fh_temps) - 1:
                fcst_slope_at_t = fh_temps[h_idx] - fh_temps[h_idx - 1]  # °F/hr
                slope_before = fh_temps[h_idx - 1] - fh_temps[h_idx - 2] if h_idx >= 2 else fcst_slope_at_t
                fcst_accel_at_t = fcst_slope_at_t - slope_before  # °F/hr²

        # --- Forecast tracking: compare obs to forecast for hours up to now ---
        # For each forecast hour <= cur_hour, find nearest observation temp
        errors = []
        for fi in range(len(fh_hours)):
            fh = fh_hours[fi]
            if fh > cur_hour:
                break
            if fh < hours[0]:
                continue
            # Find observation closest to this forecast hour
            diffs = np.abs(hours[:as_of_idx + 1] - fh)
            closest = int(np.argmin(diffs))
            if diffs[closest] < 0.75:  # within 45 min
                errors.append(temps[closest] - fh_temps[fi])

        if len(errors) >= 3:
            err_arr = np.array(errors)
            fcst_tracking_bias = float(np.mean(err_arr))
            fcst_tracking_rmse = float(np.sqrt(np.mean(err_arr ** 2)))
            fcst_tracking_max_err = float(np.max(np.abs(err_arr)))
            fcst_obs_above_pct = float(np.mean(err_arr > 0))

        # Last-hour tracking: forecast accuracy in the most recent hour only
        recent_errors = []
        for fi in range(len(fh_hours)):
            fh = fh_hours[fi]
            if fh > cur_hour or fh < cur_hour - 1.0:
                continue
            diffs = np.abs(hours[:as_of_idx + 1] - fh)
            closest = int(np.argmin(diffs))
            if diffs[closest] < 0.75:
                recent_errors.append(temps[closest] - fh_temps[fi])
        if len(recent_errors) >= 1:
            re_arr = np.array(recent_errors)
            fcst_tracking_bias_1h = float(np.mean(re_arr))
            fcst_tracking_rmse_1h = float(np.sqrt(np.mean(re_arr ** 2)))

    # --- Yesterday's weather (6) ---
    yest = yesterday or {}
    yest_high_f = yest.get("high_f", cur_max)
    yest_low_f = yest.get("low_f", cur_max - 10.0)
    yest_range_f = yest_high_f - yest_low_f
    yest_peak_hour = yest.get("peak_hour", 14.0)
    high_delta_f = cur_max - yest_high_f
    yest_high_vs_fcst = yest.get("high_vs_forecast_f", 0.0)

    return {
        # Time (5)
        "hour_decimal": round(hour_decimal, 3),
        "hours_since_solar_noon": round(hours_since_solar_noon, 3),
        "day_of_year_sin": round(day_of_year_sin, 4),
        "day_of_year_cos": round(day_of_year_cos, 4),
        "pct_daylight_elapsed": round(pct_daylight_elapsed, 4),
        # Temperature state (4)
        "margin_below_max": round(margin_below_max, 2),
        "time_since_max_hours": round(time_since_max_hours, 3),
        "readings_since_max": readings_since_max,
        "temp_range_so_far": round(temp_range_so_far, 2),
        # Momentum (7)
        "ma_cross": round(cur_ma_cross, 3),
        "rate_f_per_hr": round(cur_rate, 3),
        "ma_short_minus_max": round(ma_short_minus_max, 3),
        "rate_30m_ago": round(rate_30m_ago, 3),
        "rate_1h_ago": round(rate_1h_ago, 3),
        "rate_2h_ago": round(rate_2h_ago, 3),
        "rate_change": round(rate_change, 3),
        "accel_30m": round(accel_30m, 3),
        "accel_1h": round(accel_1h, 3),
        "accel_2h": round(accel_2h, 3),
        "accel_change": round(accel_change, 3),
        "n_declining_readings": n_declining,
        "max_decline_from_peak": round(max_decline_from_peak, 2),
        "decline_confidence": round(decline_confidence, 3),
        # Peak shape (4)
        "readings_at_max": readings_at_max,
        "time_at_max_hours": round(time_at_max_hours, 3),
        "readings_near_max_1f": readings_near_max_1f,
        "pct_at_or_near_max": round(pct_at_or_near_max, 4),
        # Trajectory (5)
        "temp_above_ma_long": round(temp_above_ma_long, 3),
        "slope_2h": round(slope_2h, 3),
        "slope_1h": round(slope_1h, 3),
        "slope_30m": round(slope_30m, 3),
        "slope_change_2h_to_30m": round(slope_change_2h_to_30m, 3),
        # Meteorological (5)
        "wind_speed_mph": round(wind_speed_mph, 2),
        "dewpoint_f": round(dewpoint_f, 2),
        "relative_humidity_pct": round(relative_humidity_pct, 2),
        "pressure_tendency": round(pressure_tendency, 3),
        "wind_change_1h": round(wind_change_1h, 2),
        # Forecast daily (3)
        "forecast_gap_f": round(forecast_gap_f, 2),
        "forecast_gap_pct": round(forecast_gap_pct, 4),
        "current_vs_forecast": round(current_vs_forecast, 2),
        # Forecast curve (7)
        "fcst_hours_since_peak": round(fcst_hours_since_peak, 3),
        "fcst_peak_hour": round(fcst_peak_hour, 1),
        "fcst_peak_before_sunrise": 1.0 if fcst_peak_hour < (solar_noon_hour - 6) else 0.0,
        "fcst_remaining_vs_cur": round(fcst_remaining_vs_cur, 2),
        "fcst_near_peak_1f": fcst_near_peak_1f,
        "fcst_near_peak_2f": fcst_near_peak_2f,
        "fcst_slope_at_t": round(fcst_slope_at_t, 2),
        "fcst_accel_at_t": round(fcst_accel_at_t, 2),
        "fcst_plateau_hours": fcst_plateau_hours,
        # Forecast derivative profile (6)
        "fcst_d1_at_peak": round(fcst_d1_at_peak, 3),
        "fcst_d1_max": round(fcst_d1_max, 3),
        "fcst_d1_min": round(fcst_d1_min, 3),
        "fcst_d2_at_peak": round(fcst_d2_at_peak, 3),
        "fcst_d2_min": round(fcst_d2_min, 3),
        "fcst_d1_post_mean": round(fcst_d1_post_mean, 3),
        # Forecast tracking accuracy (4)
        "fcst_tracking_bias": round(fcst_tracking_bias, 3),
        "fcst_tracking_rmse": round(fcst_tracking_rmse, 3),
        "fcst_tracking_max_err": round(fcst_tracking_max_err, 3),
        "fcst_obs_above_pct": round(fcst_obs_above_pct, 4),
        "fcst_tracking_bias_1h": round(fcst_tracking_bias_1h, 3),
        "fcst_tracking_rmse_1h": round(fcst_tracking_rmse_1h, 3),
        # Rounding (3)
        "boundary_distance": round(boundary_distance, 4),
        "n_possible_f": n_possible_f,
        "cur_f_fractional": round(cur_f_fractional, 4),
        # METAR (5)
        "has_metar": has_metar,
        "metar_gap_c": round(metar_gap_c, 4),
        "metar_confirm": round(metar_confirm, 4),
        "metar_above_boundary": metar_above_boundary,
        "metar_boundary_margin_c": round(metar_boundary_margin_c, 4),
        # Yesterday (6)
        "yest_high_f": round(yest_high_f, 2),
        "yest_low_f": round(yest_low_f, 2),
        "yest_range_f": round(yest_range_f, 2),
        "yest_peak_hour": round(yest_peak_hour, 2),
        "high_delta_f": round(high_delta_f, 2),
        "yest_high_vs_fcst": round(yest_high_vs_fcst, 2),
        # Labels
        LABEL: will_increase,
        "will_increase_2f": will_increase_2,
        "will_not_decrease": will_not_decrease,
    }


def _safe_float(df: pd.DataFrame, col: str, idx: int) -> float:
    """Get a float value from a DataFrame column at index, defaulting to 0."""
    if col not in df.columns:
        return 0.0
    val = df[col].iloc[idx]
    if pd.isna(val):
        return 0.0
    return float(val)


FEATURE_COLS = [
    # Time (5)
    "hour_decimal", "hours_since_solar_noon",
    "day_of_year_sin", "day_of_year_cos", "pct_daylight_elapsed",
    # Temperature state (4)
    "margin_below_max", "time_since_max_hours", "readings_since_max",
    "temp_range_so_far",
    # Momentum (12)
    "ma_cross", "rate_f_per_hr", "ma_short_minus_max",
    "rate_30m_ago", "rate_1h_ago", "rate_2h_ago",
    "rate_change",
    "accel_30m", "accel_1h", "accel_2h", "accel_change",
    "n_declining_readings",
    "max_decline_from_peak",
    "decline_confidence",
    # Peak shape (4)
    "readings_at_max", "time_at_max_hours", "readings_near_max_1f",
    "pct_at_or_near_max",
    # Trajectory (5)
    "temp_above_ma_long", "slope_2h", "slope_1h", "slope_30m",
    "slope_change_2h_to_30m",
    # Meteorological (5)
    "wind_speed_mph", "dewpoint_f", "relative_humidity_pct",
    "pressure_tendency", "wind_change_1h",
    # Forecast daily (3)
    "forecast_gap_f", "forecast_gap_pct", "current_vs_forecast",
    # Forecast curve (7)
    "fcst_hours_since_peak", "fcst_peak_hour",
    "fcst_peak_before_sunrise", "fcst_remaining_vs_cur",
    "fcst_near_peak_1f", "fcst_near_peak_2f",
    "fcst_slope_at_t", "fcst_accel_at_t", "fcst_plateau_hours",
    # Forecast derivative profile (6)
    "fcst_d1_at_peak", "fcst_d1_max", "fcst_d1_min",
    "fcst_d2_at_peak", "fcst_d2_min", "fcst_d1_post_mean",
    # Forecast tracking accuracy (4)
    "fcst_tracking_bias", "fcst_tracking_rmse",
    "fcst_tracking_max_err", "fcst_obs_above_pct",
    "fcst_tracking_bias_1h", "fcst_tracking_rmse_1h",
    # Rounding (3)
    "boundary_distance", "n_possible_f", "cur_f_fractional",
    # METAR (5)
    "has_metar", "metar_gap_c", "metar_confirm",
    "metar_above_boundary", "metar_boundary_margin_c",
    # Yesterday (6)
    "yest_high_f", "yest_low_f", "yest_range_f",
    "yest_peak_hour", "high_delta_f", "yest_high_vs_fcst",
]


# ---------------------------------------------------------------------------
# Day sampling
# ---------------------------------------------------------------------------

def _compute_actual_max_c(day_df: pd.DataFrame) -> Optional[float]:
    """End-of-day ground truth max °C from 6h METAR readings (skip before 01:00)."""
    if "max_temp_6h_c" not in day_df.columns:
        raise ValueError("max_temp_6h_c column missing — re-fetch history data")
    _m6h = day_df[day_df["max_temp_6h_c"].notna() & (day_df["ts"].dt.hour >= 1)]
    if _m6h.empty:
        return None  # no daytime 6h METAR readings this day
    val = pd.to_numeric(_m6h["max_temp_6h_c"], errors="coerce").max()
    if np.isnan(val):
        return None
    return float(val)


def generate_day_samples(
    site: str,
    day_df: pd.DataFrame,
    precomp: dict,
    solar_noon_hour: float,
    actual_max_c: float,
    forecast_high_f: float,
    rng: np.random.RandomState,
    oversample: int = 1,
    forecast_hourly: Optional[List[Tuple[int, float]]] = None,
    yesterday: Optional[dict] = None,
) -> List[dict]:
    """3 random from [peak-2h, peak), 3 near peak temp, 2 from (peak, peak+1h].

    oversample: repeat sampling this many times (with replacement after first
    pass) to boost positive-day representation.
    """
    hours = precomp["hours"]
    temps = precomp["temps"]
    running_max = precomp["running_max"]
    peak_hour = precomp["peak_hour"]
    samples = []

    def _sample(indices: np.ndarray, k: int, allow_replace: bool = False) -> List[int]:
        if len(indices) == 0:
            return []
        if len(indices) <= k and not allow_replace:
            return list(indices)
        return list(rng.choice(indices, size=k, replace=allow_replace or len(indices) < k))

    # 1) [peak-2h, peak) — approaching peak
    pre_mask = (hours >= peak_hour - 2.0) & (hours < peak_hour)
    pre_indices = np.where(pre_mask)[0]

    # 2) Near peak temp (within 1°F of running max)
    peak_temp = running_max[-1]  # final running max = daily high
    near_mask = (np.abs(temps - peak_temp) <= 1.0) & (hours >= peak_hour - 1.0) & (hours <= peak_hour + 1.0)
    near_indices = np.where(near_mask)[0]

    # 3) (peak, peak+1h] — just after peak
    post_mask = (hours > peak_hour) & (hours <= peak_hour + 1.0)
    post_indices = np.where(post_mask)[0]

    chosen = _sample(pre_indices, 3) + _sample(near_indices, 3) + _sample(post_indices, 2)
    # Additional oversample passes with replacement
    for _ in range(oversample - 1):
        chosen += _sample(pre_indices, 3, allow_replace=True) \
                + _sample(near_indices, 3, allow_replace=True) \
                + _sample(post_indices, 2, allow_replace=True)

    for idx in chosen:
        feat = extract_peak_features(
            day_df, precomp, idx, solar_noon_hour, actual_max_c, forecast_high_f,
            forecast_hourly=forecast_hourly, yesterday=yesterday)
        if feat is not None:
            feat["site"] = site
            feat["date"] = str(day_df["date"].iloc[0])
            samples.append(feat)

    return samples


# ---------------------------------------------------------------------------
# Load all samples
# ---------------------------------------------------------------------------

def load_all_samples(sites: Optional[List[str]] = None, since: Optional[str] = None) -> pd.DataFrame:
    """Load all sites, precompute momentum, generate samples."""

    if sites is None:
        sites = list(ALL_SITES)

    # Load solar noon cache
    solar_noon_lookup: Dict[Tuple[str, str], float] = {}
    if os.path.isfile(SOLAR_NOON_CSV):
        sn_df = pd.read_csv(SOLAR_NOON_CSV)
        for _, row in sn_df.iterrows():
            solar_noon_lookup[(row["site"], str(row["date"]))] = float(row["solar_noon_hour"])
        print(f"  Loaded {len(solar_noon_lookup)} solar noon entries")
    else:
        print(f"  No solar noon cache — using fallback (12.0)")

    # Load Open-Meteo historical forecast highs
    forecast_lookup = load_forecast_highs()
    n_forecast = len(forecast_lookup)
    if n_forecast:
        print(f"  Loaded {n_forecast} Open-Meteo forecast entries")
    else:
        print(f"  No Open-Meteo forecasts — using rolling 7-day fallback")

    # Load Open-Meteo hourly forecasts
    forecast_hourly_lookup = load_forecast_hourly()
    n_hourly = len(forecast_hourly_lookup)
    if n_hourly:
        print(f"  Loaded {n_hourly} Open-Meteo hourly forecast days")
    else:
        print(f"  No hourly forecasts — forecast curve features will use defaults")

    import time as _time
    rng = np.random.RandomState(42)
    all_rows: List[dict] = []
    total_days = 0
    skipped = 0
    n_forecast_hits = 0
    n_fallback = 0
    _t_load = 0.0
    _t_precomp = 0.0
    _t_samples = 0.0

    for site in sites:
        _t_site_start = _time.time()
        _t0 = _time.time()
        df = load_site_history(site)
        _t_load += _time.time() - _t0
        if df.empty:
            print(f"  {site}: no data")
            continue

        # Build rolling fallback for dates missing from Open-Meteo
        forecast_fallback = build_forecast_fallback(df)

        # Precompute per-day summaries for yesterday features
        all_day_groups = list(df.groupby("date"))
        day_groups = [(date, grp.sort_values("ts").reset_index(drop=True))
                      for date, grp in all_day_groups
                      if len(grp) >= 200 and (since is None or str(date) >= since)]
        skipped += len(all_day_groups) - len(day_groups)
        day_groups.sort(key=lambda x: x[0])

        # Build yesterday lookup: {date_str: summary_dict}
        day_summaries: Dict[str, dict] = {}
        for date, day_df in day_groups:
            temps_f = day_df["temperature_f"].astype(float)
            high_f = float(temps_f.max())
            low_f = float(temps_f.min())
            peak_idx = int(temps_f.idxmax())
            hours_arr = (pd.to_datetime(day_df["timestamp"].str[:19])
                         - pd.to_datetime(day_df["timestamp"].str[:10])).dt.total_seconds() / 3600.0
            peak_hour = float(hours_arr.iloc[peak_idx])
            date_str = str(date)
            om_fcst = forecast_lookup.get((site, date_str))
            fb_fcst = forecast_fallback.get(date_str, 70.0)
            fcst_high = om_fcst if om_fcst is not None else fb_fcst
            day_summaries[date_str] = {
                "high_f": high_f,
                "low_f": low_f,
                "peak_hour": peak_hour,
                "high_vs_forecast_f": high_f - fcst_high,
            }

        site_days = 0
        prev_summary: Optional[dict] = None
        for date, day_df in day_groups:
            actual_max_c = _compute_actual_max_c(day_df)
            if actual_max_c is None:
                skipped += 1
                prev_summary = day_summaries.get(str(date))
                continue

            date_str = str(date)
            om_val = forecast_lookup.get((site, date_str))
            if om_val is not None:
                forecast_high_f = om_val
                n_forecast_hits += 1
            else:
                forecast_high_f = forecast_fallback.get(date_str, 70.0)
                n_fallback += 1

            # Skip data up to any 6h METAR before 01:00 — its max/min
            # covers the previous evening and contaminates running accumulators.
            if "max_temp_6h_f" in day_df.columns:
                _early_metar = day_df[
                    day_df["max_temp_6h_f"].notna() & (day_df["ts"].dt.hour < 1)
                ]
                if not _early_metar.empty:
                    _cutoff_idx = _early_metar.index[-1] + 1
                    day_df = day_df.iloc[_cutoff_idx:].reset_index(drop=True)
                    if len(day_df) < 200:
                        skipped += 1
                        prev_summary = day_summaries.get(date_str)
                        continue

            _t0 = _time.time()
            precomp = precompute_day_momentum(day_df)
            # precompute_day_momentum already calls compute_momentum internally;
            # reuse its result instead of computing again (O(n²) per day).
            precomp["_mom_df"] = precomp.get("_mom_df")
            _t_precomp += _time.time() - _t0

            # Determine if this is a positive day (naive_f will shift +1)
            # to oversample it for class balance
            running_auto_max_c = precomp["running_auto_max_c"]
            final_auto_c = running_auto_max_c[~np.isnan(running_auto_max_c)]
            if len(final_auto_c) > 0:
                cur_naive_f = round(float(final_auto_c[-1]) * 9.0 / 5.0 + 32.0)
                actual_naive_f = round(float(actual_max_c) * 9.0 / 5.0 + 32.0)
                is_positive_day = actual_naive_f >= cur_naive_f + 1
            else:
                is_positive_day = False
            oversample = 2 if is_positive_day else 1

            _t0 = _time.time()
            sn = solar_noon_lookup.get((site, str(date)), 12.0)
            fh = forecast_hourly_lookup.get((site, date_str))
            samples = generate_day_samples(
                site, day_df, precomp, sn, actual_max_c, forecast_high_f, rng,
                oversample=oversample, forecast_hourly=fh, yesterday=prev_summary)
            all_rows.extend(samples)
            _t_samples += _time.time() - _t0
            site_days += 1
            prev_summary = day_summaries.get(date_str)

        total_days += site_days
        _t_site = _time.time() - _t_site_start
        print(f"  {site}: {site_days} days, {len(all_rows)} samples  ({_t_site:.1f}s)")
        sys.stdout.flush()

    print(f"  Total: {total_days} days, {len(all_rows)} samples "
          f"({skipped} days skipped)")
    print(f"  Forecast source: {n_forecast_hits} Open-Meteo, {n_fallback} rolling fallback")
    print(f"  Timing: load={_t_load:.1f}s  precomp={_t_precomp:.1f}s  samples={_t_samples:.1f}s")

    if not all_rows:
        return pd.DataFrame()
    return pd.DataFrame(all_rows)


# ---------------------------------------------------------------------------
# Training and evaluation
# ---------------------------------------------------------------------------

def _build_models() -> list:
    """Return list of (name, model) tuples."""
    from sklearn.experimental import enable_hist_gradient_boosting  # noqa: F401
    from sklearn.ensemble import HistGradientBoostingClassifier

    return [
        ("HistGBM", HistGradientBoostingClassifier(
            max_iter=400, max_depth=7, learning_rate=0.2,
            min_samples_leaf=20, random_state=42)),
    ]


def _run_loso_sweep(df: pd.DataFrame, label_col: str, label_name: str) -> dict:
    """Run LOSO CV model sweep for a given label column.

    Returns dict with best model name, full-trained model, and metrics.
    """
    from sklearn.metrics import (
        accuracy_score, precision_score, recall_score, f1_score,
        classification_report,
    )
    from sklearn.base import clone

    all_sites = sorted(df["site"].unique())
    # Only test on Kalshi sites, training-only sites always stay in training set
    test_sites = sorted(s for s in all_sites if s in ALL_SITES)
    train_only_sites = sorted(s for s in all_sites if s not in ALL_SITES)
    models = _build_models()

    print(f"\n{'=' * 70}")
    print(f"  LEAVE-ONE-SITE-OUT CV — {label_name}")
    print(f"  Test sites: {len(test_sites)} (Kalshi)  |  Train-only: {len(train_only_sites)}")
    print(f"  Test data: 2026-01-01 onward")
    print(f"{'=' * 70}")

    pos_rate = df[label_col].mean()
    baseline_acc = max(pos_rate, 1 - pos_rate)
    baseline_label = "always-0" if pos_rate < 0.5 else "always-1"
    n_pos = int((df[label_col] == 1).sum())
    n_neg = len(df) - n_pos
    print(f"  Class balance: {n_pos} positive ({n_pos / len(df):.1%}), "
          f"{n_neg} negative ({n_neg / len(df):.1%})")
    print(f"  Baseline ({baseline_label}): {baseline_acc:.1%}\n")

    model_results = {}

    for model_name, model_template in models:
        all_y_true = []
        all_y_pred = []
        all_y_prob = []
        all_sites_list = []
        per_site = []

        for test_site in test_sites:
            # Train: all other sites (including train-only) + test site's pre-2026 data
            test_mask = (df["site"] == test_site) & (df["date"] >= "2026-01-01")
            train_df = df[~test_mask]
            test_df = df[test_mask]
            if len(test_df) < 10:
                continue

            X_train = train_df[FEATURE_COLS].values
            y_train = train_df[label_col].values
            X_test = test_df[FEATURE_COLS].values
            y_test = test_df[label_col].values

            model = clone(model_template)
            model.fit(X_train, y_train)
            y_pred = model.predict(X_test)

            if hasattr(model, "predict_proba"):
                y_prob = model.predict_proba(X_test)[:, 1]
            else:
                y_prob = y_pred.astype(float)

            acc = accuracy_score(y_test, y_pred)
            f1 = f1_score(y_test, y_pred, zero_division=0)

            per_site.append({
                "site": test_site,
                "n_test": len(test_df),
                "accuracy": acc,
                "f1": f1,
                "pos_pct": float(y_test.mean()),
            })

            all_y_true.extend(y_test)
            all_y_pred.extend(y_pred)
            all_y_prob.extend(y_prob)
            all_sites_list.extend([test_site] * len(y_test))

        all_y_true = np.array(all_y_true)
        all_y_pred = np.array(all_y_pred)
        all_y_prob = np.array(all_y_prob)

        overall_acc = accuracy_score(all_y_true, all_y_pred)
        overall_f1 = f1_score(all_y_true, all_y_pred, zero_division=0)
        overall_prec = precision_score(all_y_true, all_y_pred, zero_division=0)
        overall_rec = recall_score(all_y_true, all_y_pred, zero_division=0)

        model_results[model_name] = {
            "per_site": per_site,
            "accuracy": overall_acc,
            "f1": overall_f1,
            "precision": overall_prec,
            "recall": overall_rec,
            "y_true": all_y_true,
            "y_pred": all_y_pred,
            "y_prob": all_y_prob,
            "sites": all_sites_list,
        }

    # --- Model comparison table ---
    print(f"  {'Model':<22s} {'Acc':>7s} {'Prec':>7s} {'Rec':>7s} {'F1':>7s}")
    print(f"  {'-'*22} {'-'*7} {'-'*7} {'-'*7} {'-'*7}")
    print(f"  {baseline_label:<22s} {baseline_acc:>7.4f} {'—':>7s} {'—':>7s} {'—':>7s}")

    best_name = None
    best_f1 = -1.0
    for name in [n for n, _ in models]:
        r = model_results[name]
        if r["f1"] > best_f1:
            best_f1 = r["f1"]
            best_name = name
        print(f"  {name:<22s} {r['accuracy']:>7.4f} {r['precision']:>7.4f} "
              f"{r['recall']:>7.4f} {r['f1']:>7.4f}")

    print(f"\n  Best model: {best_name} (F1={best_f1:.4f})")

    # --- Detailed results for best model ---
    best = model_results[best_name]

    print(f"\n{'=' * 70}")
    print(f"  {best_name} — DETAILED RESULTS ({label_name})")
    print(f"{'=' * 70}")
    print(classification_report(
        best["y_true"], best["y_pred"],
        target_names=[f"no_{label_name}", label_name]))

    # Per-site breakdown
    print(f"  PER-SITE ACCURACY")
    print(f"  {'Site':<6} {'N':>6} {'Acc':>7} {'F1':>7} {'Pos%':>7}")
    print(f"  {'-'*6} {'-'*6} {'-'*7} {'-'*7} {'-'*7}")
    for ps in best["per_site"]:
        print(f"  {ps['site']:<6} {ps['n_test']:>6} {ps['accuracy']:>7.4f} "
              f"{ps['f1']:>7.4f} {ps['pos_pct']:>6.1%}")

    accs = [ps["accuracy"] for ps in best["per_site"]]
    f1s = [ps["f1"] for ps in best["per_site"]]
    print(f"\n  Mean accuracy: {np.mean(accs):.4f} ± {np.std(accs):.4f}")
    print(f"  Mean F1:       {np.mean(f1s):.4f} ± {np.std(f1s):.4f}")

    # Feature importances — train best model on full data
    for name, tmpl in _build_models():
        if name == best_name:
            full_model = clone(tmpl)
            break
    X_all = df[FEATURE_COLS].values
    y_all = df[label_col].values
    full_model.fit(X_all, y_all)
    if hasattr(full_model, "feature_importances_"):
        _print_feature_importances(full_model, FEATURE_COLS)

    # Calibration
    _print_calibration(best["y_true"], best["y_prob"])

    # SHAP plots
    try:
        import shap
        import matplotlib
        matplotlib.use("Agg")
        import matplotlib.pyplot as plt
        from paths import project_path

        chart_dir = project_path("charts", "peak")
        os.makedirs(chart_dir, exist_ok=True)
        safe_label = label_name.replace("°", "").replace(">", "gt")

        explainer = shap.TreeExplainer(full_model)
        X_df = pd.DataFrame(X_all, columns=FEATURE_COLS)
        shap_values = explainer(X_df)

        # Summary dot plot
        plt.figure(figsize=(10, 8))
        shap.summary_plot(shap_values.values, X_df, max_display=20, show=False)
        plt.title(f"SHAP — {label_name}")
        plt.tight_layout()
        path = os.path.join(chart_dir, f"shap_peak_{safe_label}.png")
        plt.savefig(path, dpi=150)
        plt.close()
        print(f"  Saved {path}")

        # Bar plot (mean |SHAP|)
        plt.figure(figsize=(10, 8))
        shap.summary_plot(shap_values.values, X_df, max_display=20, show=False, plot_type="bar")
        plt.title(f"SHAP bar — {label_name}")
        plt.tight_layout()
        path = os.path.join(chart_dir, f"shap_peak_{safe_label}_bar.png")
        plt.savefig(path, dpi=150)
        plt.close()
        print(f"  Saved {path}")

        # Per-feature dependence plots (top 15 by mean |SHAP|)
        mean_abs_shap = np.mean(np.abs(shap_values.values), axis=0)
        top_idx = np.argsort(mean_abs_shap)[::-1][:15]
        feat_dir = os.path.join(chart_dir, f"shap_peak_{safe_label}_features")
        os.makedirs(feat_dir, exist_ok=True)
        for rank, fi in enumerate(top_idx):
            feat_name = FEATURE_COLS[fi]
            plt.figure(figsize=(8, 5))
            shap.dependence_plot(feat_name, shap_values.values, X_df, show=False)
            plt.title(f"SHAP — {feat_name} ({label_name})")
            plt.tight_layout()
            fpath = os.path.join(feat_dir, f"{rank:02d}_{feat_name}.png")
            plt.savefig(fpath, dpi=120)
            plt.close()
        print(f"  Saved {len(top_idx)} per-feature plots to {feat_dir}")
    except Exception as e:
        print(f"  SHAP plots failed: {e}")

    return {
        "model_name": best_name,
        "model": full_model,
        "accuracy": best["accuracy"],
        "f1": best["f1"],
        "per_site": best["per_site"],
        "all_results": {k: {
            "accuracy": v["accuracy"], "f1": v["f1"],
            "precision": v["precision"], "recall": v["recall"],
        } for k, v in model_results.items()},
    }


def train_and_evaluate(df: pd.DataFrame) -> dict:
    """Leave-one-site-out CV for >=0°F, >1°F and >2°F labels."""

    # >=0°F (will not decrease)
    LABEL_0 = "will_not_decrease"
    result_0f = None
    if LABEL_0 in df.columns:
        result_0f = _run_loso_sweep(df, LABEL_0, ">=0°F")

    # >1°F
    result_1f = _run_loso_sweep(df, LABEL, ">1°F")

    # >2°F
    LABEL_2 = "will_increase_2f"
    result_2f = None
    if LABEL_2 in df.columns:
        result_2f = _run_loso_sweep(df, LABEL_2, ">2°F")

    return {
        "model_name": result_1f["model_name"],
        "model": result_1f["model"],
        "accuracy": result_1f["accuracy"],
        "f1": result_1f["f1"],
        "per_site": result_1f["per_site"],
        "all_results": result_1f["all_results"],
        "result_0f": result_0f,
        "result_2f": result_2f,
    }


# ---------------------------------------------------------------------------
# Analysis helpers
# ---------------------------------------------------------------------------

def _print_feature_importances(model, feature_cols: list, top_n: int = 15) -> None:
    importances = model.feature_importances_
    indices = np.argsort(importances)[::-1]

    print(f"\n  TOP {top_n} FEATURE IMPORTANCES")
    print(f"  {'-' * 40}")
    for rank, idx in enumerate(indices[:top_n], 1):
        print(f"  {rank:>2}. {feature_cols[idx]:<30s} {importances[idx]:.4f}")


def _print_per_site_accuracy(test_df: pd.DataFrame, y_pred: np.ndarray) -> None:
    meta = test_df.copy().reset_index(drop=True)
    meta["y_pred"] = y_pred

    print(f"\n  PER-SITE ACCURACY")
    print(f"  {'Site':<6} {'N':>6} {'Acc':>7} {'Pos%':>7}")
    print(f"  {'-'*6} {'-'*6} {'-'*7} {'-'*7}")

    for site in sorted(meta["site"].unique()):
        site_mask = meta["site"] == site
        site_df = meta[site_mask]
        y_t = site_df[LABEL].values
        y_p = site_df["y_pred"].values
        acc = (y_t == y_p).mean()
        pos = y_t.mean()
        print(f"  {site:<6} {len(site_df):>6} {acc:>7.4f} {pos:>6.1%}")


def _print_calibration(y_true: np.ndarray, y_prob: np.ndarray, n_bins: int = 10) -> None:
    print(f"\n  CALIBRATION TABLE ({n_bins} bins)")
    print(f"  {'Bin':>12s} {'Count':>7} {'Mean pred':>10} {'Mean actual':>12} {'Gap':>7}")
    print(f"  {'-'*12} {'-'*7} {'-'*10} {'-'*12} {'-'*7}")

    bin_edges = np.linspace(0, 1, n_bins + 1)
    for i in range(n_bins):
        lo, hi = bin_edges[i], bin_edges[i + 1]
        mask = (y_prob >= lo) & (y_prob < hi) if i < n_bins - 1 else (y_prob >= lo) & (y_prob <= hi)
        count = mask.sum()
        if count == 0:
            continue
        mean_pred = y_prob[mask].mean()
        mean_actual = y_true[mask].mean()
        gap = mean_pred - mean_actual
        print(f"  [{lo:.1f}, {hi:.1f}) {count:>7} {mean_pred:>10.4f} {mean_actual:>12.4f} {gap:>+7.4f}")


def _plot_feature_distributions(df: pd.DataFrame) -> None:
    """Plot feature distributions split by class label."""
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt

    pos = df[df[LABEL] == 1]
    neg = df[df[LABEL] == 0]
    n_features = len(FEATURE_COLS)
    n_cols = 4
    n_rows = math.ceil(n_features / n_cols)

    fig, axes = plt.subplots(n_rows, n_cols, figsize=(5 * n_cols, 3.5 * n_rows))
    axes = axes.flatten()

    for i, col in enumerate(FEATURE_COLS):
        ax = axes[i]
        lo = df[col].quantile(0.01)
        hi = df[col].quantile(0.99)
        bins = np.linspace(lo, hi, 40)
        ax.hist(neg[col].clip(lo, hi), bins=bins, alpha=0.5, density=True,
                color="tab:blue", label="no increase")
        ax.hist(pos[col].clip(lo, hi), bins=bins, alpha=0.5, density=True,
                color="tab:red", label="will increase")
        ax.set_title(col, fontsize=9)
        ax.tick_params(labelsize=7)
        if i == 0:
            ax.legend(fontsize=7)

    # Hide unused subplots
    for j in range(n_features, len(axes)):
        axes[j].set_visible(False)

    fig.suptitle(f"Feature Distributions by {LABEL} (n={len(df)})", fontsize=13)
    plt.tight_layout()
    out_path = project_path("charts", "weather", "peak_feature_distributions.png")
    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    plt.savefig(out_path, dpi=120)
    plt.close()
    print(f"  Saved to {out_path}")


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def tune_histgbm(df: pd.DataFrame) -> None:
    """Grid search HistGBM hyperparameters using StratifiedKFold."""
    from sklearn.experimental import enable_hist_gradient_boosting  # noqa: F401
    from sklearn.ensemble import HistGradientBoostingClassifier
    from sklearn.model_selection import GridSearchCV, StratifiedKFold

    X = df[FEATURE_COLS].values
    y = df[LABEL].values
    n = len(df)

    param_grid = {
        "max_iter": [100, 200, 400],
        "max_depth": [3, 4, 5, 7],
        "learning_rate": [0.05, 0.1, 0.2],
        "min_samples_leaf": [5, 10, 20],
    }

    n_combos = 1
    for v in param_grid.values():
        n_combos *= len(v)

    print(f"\n{'=' * 78}")
    print(f"  HISTGBM HYPERPARAMETER TUNING ({n} rows, {len(FEATURE_COLS)} features)")
    print(f"{'=' * 78}")

    cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
    gs = GridSearchCV(
        HistGradientBoostingClassifier(random_state=42, early_stopping=True,
                                       n_iter_no_change=10),
        param_grid, cv=cv, scoring="f1", n_jobs=-1, verbose=1,
    )
    gs.fit(X, y)

    print(f"\n  Best params: {gs.best_params_}")
    print(f"  Best CV F1: {gs.best_score_:.4f}")

    results_df = pd.DataFrame(gs.cv_results_).sort_values("rank_test_score")
    print(f"\n  Top 10 configurations:")
    print(f"  {'Rank':>4s} {'F1':>9s} {'max_iter':>9s} {'depth':>5s}"
          f" {'lr':>6s} {'min_leaf':>8s}")
    print(f"  {'----':>4s} {'-'*9} {'-'*9} {'-'*5} {'-'*6} {'-'*8}")
    for _, row in results_df.head(10).iterrows():
        print(f"  {int(row['rank_test_score']):>4d}"
              f" {row['mean_test_score']:>9.4f}"
              f" {int(row['param_max_iter']):>9d}"
              f" {int(row['param_max_depth']):>5d}"
              f" {row['param_learning_rate']:>6.2f}"
              f" {int(row['param_min_samples_leaf']):>8d}")


def main() -> None:
    parser = argparse.ArgumentParser(description="Peak detection backtest")
    parser.add_argument("--site", type=str, default=None,
                        help="Comma-separated ICAO codes (default: all)")
    parser.add_argument("--save", action="store_true",
                        help="Persist trained model to disk")
    parser.add_argument("--plot-features", action="store_true",
                        help="Plot feature distributions per class label")
    parser.add_argument("--use-all-sites", action="store_true",
                        help="Include all training sites (default: Kalshi sites only)")
    parser.add_argument("--since", type=str, default=None,
                        help="Only use data from this date (YYYY-MM-DD)")
    parser.add_argument("--tune", action="store_true",
                        help="Grid search HistGBM hyperparameters")
    args = parser.parse_args()

    sites = args.site.split(",") if args.site else None
    if sites is None and args.use_all_sites:
        sites = list(ALL_SITES_WITH_TRAINING)

    print("=" * 70)
    print("  PEAK DETECTION BACKTEST")
    print(f"  Label: {LABEL} = 1 if round(actual_max_c→°F) >= round(running_auto_max_c→°F) + 1")
    print(f"  Split: Leave-one-site-out CV")
    print(f"  Sampling: 3 pre-peak + 3 near peak temp + 2 post-peak")
    print(f"  Forecast: Open-Meteo historical highs (fallback: rolling 7-day mean)")
    print("=" * 70)
    print()

    print("Loading and generating samples...")
    df = load_all_samples(sites, since=args.since)
    if df.empty:
        print("No samples generated. Check data files.")
        sys.exit(1)

    n_sites = df["site"].nunique()
    n_days = df.groupby(["site", "date"]).ngroups
    n_pos = (df[LABEL] == 1).sum()
    n_neg = (df[LABEL] == 0).sum()
    print(f"\n  Dataset: {len(df)} samples, {n_days} site-days, {n_sites} sites")
    print(f"  Class balance: {n_pos} positive ({n_pos / len(df):.1%}), "
          f"{n_neg} negative ({n_neg / len(df):.1%})")

    if args.plot_features:
        _plot_feature_distributions(df)
        return

    if args.tune:
        tune_histgbm(df)
        return

    results = train_and_evaluate(df)

    if args.save:
        model = results.get("model")
        if model is not None:
            os.makedirs(MODEL_DIR, exist_ok=True)
            with open(MODEL_PATH, "wb") as f:
                pickle.dump({"model": model, "features": FEATURE_COLS}, f)
            print(f"\n  Model saved to {MODEL_PATH}")

    print("\nDone.")


if __name__ == "__main__":
    main()
